### ISSUE TITLE
problems with python 3.7

### ISSUE THREAD

**Issue by fccoelho** [koji-kojiro/matplotlib-d#17] opened 2019-09-22 18:11 UTC

**Comment by fccoelho** [comment] 2019-09-22 18:20
When trying to use matplotlibd with python 3.7. This exception is raised:
```python
Traceback (most recent call last):
  File "/home/fccoelho/.dub/packages/matplotlib-d-0.1.5/matplotlib-d/python/prebuild.py", line 38, in <module>
    gen_pyplot_functions(argv[1])
  File "/home/fccoelho/.dub/packages/matplotlib-d-0.1.5/matplotlib-d/python/prebuild.py", line 27, in gen_pyplot_functions
    from string import lowercase
ImportError: cannot import name 'lowercase' from 'string' (/usr/lib/python3.7/string.py)
```
the problem is that `lowercase` is no longer a  variable of module string, on Python 3.7
this should be changed to `ascii_lowercase`

**Comment by polygonalenippel** [comment] 2019-09-23 08:25
duplicate of #15 but yeah i think the maintainer has given up or something?

**Comment by andre2007** [comment] 2019-09-23 10:09
@koji-kojiro accepting pull requests and merging them as fas as I know. Someone just has to update the python script https://github.com/koji-kojiro/matplotlib-d/blob/master/python/prebuild.py. This script generates the file https://github.com/koji-kojiro/matplotlib-d/blob/master/views/pyplot_functions.txt

I would create a pull if I would have enough python knowledge but I am really unsure about the correct solution.

**Comment by fccoelho** [comment] 2019-09-23 16:13
I'll do that as soon as I can.

**Comment by fccoelho** [comment] 2019-09-24 06:33
There is already a pull-request for this but it's stuck because of a failure on travis-CI

**Closed as completed** 2019-09-24 06:33 UTC
